name: my first workflow

on:
    push:
      

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "Hello welcome"
            
            - name: List files
              run: ls
            
            - name: Read file
              run: cat README.md