name: Usage ASCII Artwork


on:
    push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to repository
              uses: actions/checkout@v4
            
            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Executing shell script
              run: |
                chmod +x script.sh
                ./script.sh